/* =============================================
   ASKER ŞAFAK HARİTASI - VERİ DOSYASI
   ============================================= */

var TOTAL_DAYS = 180;
var PLATE_DAYS = 81;
var WAIT_DAYS = TOTAL_DAYS - PLATE_DAYS;

// GeoJSON'daki il isimlerini plaka koduna eşleştir
var CITY_NAME_TO_PLATE = {
    "adana": "01", "adiyaman": "02", "afyonkarahisar": "03", "afyon": "03",
    "agri": "04", "ağrı": "04", "amasya": "05", "ankara": "06",
    "antalya": "07", "artvin": "08", "aydin": "09", "aydın": "09",
    "balikesir": "10", "balıkesir": "10", "bilecik": "11", "bingol": "12", "bingöl": "12",
    "bitlis": "13", "bolu": "14", "burdur": "15", "bursa": "16",
    "canakkale": "17", "çanakkale": "17", "cankiri": "18", "çankırı": "18",
    "corum": "19", "çorum": "19", "denizli": "20", "diyarbakir": "21", "diyarbakır": "21",
    "edirne": "22", "elazig": "23", "elazığ": "23", "erzincan": "24", "erzurum": "25",
    "eskisehir": "26", "eskişehir": "26", "gaziantep": "27", "giresun": "28",
    "gumushane": "29", "gümüşhane": "29", "hakkari": "30", "hakkâri": "30",
    "hatay": "31", "isparta": "32", "mersin": "33", "icel": "33", "içel": "33",
    "istanbul": "34", "i̇stanbul": "34", "izmir": "35", "i̇zmir": "35",
    "kars": "36", "kastamonu": "37", "kayseri": "38",
    "kirklareli": "39", "kırklareli": "39", "kirsehir": "40", "kırşehir": "40",
    "kocaeli": "41", "konya": "42", "kutahya": "43", "kütahya": "43",
    "malatya": "44", "manisa": "45",
    "kahramanmaras": "46", "kahramanmaraş": "46", "maras": "46", "k.maraş": "46",
    "mardin": "47", "mugla": "48", "muğla": "48", "mus": "49", "muş": "49",
    "nevsehir": "50", "nevşehir": "50", "nigde": "51", "niğde": "51",
    "ordu": "52", "rize": "53", "sakarya": "54", "samsun": "55",
    "siirt": "56", "sinop": "57", "sivas": "58",
    "tekirdag": "59", "tekirdağ": "59", "tokat": "60", "trabzon": "61",
    "tunceli": "62", "sanliurfa": "63", "şanlıurfa": "63", "urfa": "63",
    "usak": "64", "uşak": "64", "van": "65", "yozgat": "66", "zonguldak": "67",
    "aksaray": "68", "bayburt": "69", "karaman": "70",
    "kirikkale": "71", "kırıkkale": "71", "batman": "72",
    "sirnak": "73", "şırnak": "73", "bartin": "74", "bartın": "74",
    "ardahan": "75", "igdir": "76", "iğdır": "76",
    "yalova": "77", "karabuk": "78", "karabük": "78",
    "kilis": "79", "osmaniye": "80", "duzce": "81", "düzce": "81"
};

var CITIES = [
    { p: "01", n: "ADANA", q: "Bu yolun sonu aydınlık, yeter ki yürümeye devam et." },
    { p: "02", n: "ADIYAMAN", q: "Nemrut'un zirvesinden baktığında her şey küçülür, dertler de." },
    { p: "03", n: "AFYONKARAHİSAR", q: "Zaferlerin şehri sana güç versin, son düzlüğe girdin." },
    { p: "04", n: "AĞRI", q: "Ağrı Dağı kadar büyük sabrın karşılığını bulacak." },
    { p: "05", n: "AMASYA", q: "Şehzadeler şehrinden selam, vatan borcu şerefli görevdir." },
    { p: "06", n: "ANKARA", q: "Başkentin kalbinden geçen yollar eve çıkar sonunda." },
    { p: "07", n: "ANTALYA", q: "Güneş her zaman bulutların arkasından çıkar." },
    { p: "08", n: "ARTVİN", q: "Yeşilin her tonunu gören gözler umudun rengini de bilir." },
    { p: "09", n: "AYDIN", q: "Her karanlık gecenin ardından aydınlık bir gün doğar." },
    { p: "10", n: "BALIKESİR", q: "İki denize komşu şehir gibi iki dünya arasındasın." },
    { p: "11", n: "BİLECİK", q: "Küçük ama güçlü, tıpkı senin azmin gibi." },
    { p: "12", n: "BİNGÖL", q: "Bin göl kadar derin duygularınla eve bir adım daha yakınsın." },
    { p: "13", n: "BİTLİS", q: "Dimdik ayakta kalan şehir gibi sen de dimdik dur." },
    { p: "14", n: "BOLU", q: "Doğanın kalbinde huzur vardır, senin kalbinde de olacak." },
    { p: "15", n: "BURDUR", q: "Göl kadar sakin ol, fırtınalar geçecek." },
    { p: "16", n: "BURSA", q: "Yeşil Bursa gibi hayatın da yeşerecek, biraz sabret." },
    { p: "17", n: "ÇANAKKALE", q: "Geçilmez denilen yeri geçenler bu milletin evlatlarıdır." },
    { p: "18", n: "ÇANKIRI", q: "Sessiz ama kararlı adımlarla hedefe ulaşılır." },
    { p: "19", n: "ÇORUM", q: "Hititlerin başkentinde sabır taşa kazınmıştır." },
    { p: "20", n: "DENİZLİ", q: "Pamukkale'nin suları gibi zamanla her şey akar gider." },
    { p: "21", n: "DİYARBAKIR", q: "Surlarla çevrili şehir gibi güçlü kalbinle çevril." },
    { p: "22", n: "EDİRNE", q: "Selimiye'nin kubbeleri gibi yükseklere bak, terhis yakın." },
    { p: "23", n: "ELAZIĞ", q: "Doğunun incisi, senin de parlama vaktin gelecek." },
    { p: "24", n: "ERZİNCAN", q: "Depremler bile yıkamadı bu şehri, seni de yıkamaz." },
    { p: "25", n: "ERZURUM", q: "Soğuğu en iyi bilen şehir, sıcak eve kavuşmanın değerini bilir." },
    { p: "26", n: "ESKİŞEHİR", q: "Gençlik şehrinden selam: Her şey güzel olacak." },
    { p: "27", n: "GAZİANTEP", q: "Gazi şehrin azmi damarlarında aksın." },
    { p: "28", n: "GİRESUN", q: "Fındık kadar küçük günler terhiste kocaman mutluluğa dönecek." },
    { p: "29", n: "GÜMÜŞHANE", q: "Gümüş gibi parlayan günler seni bekliyor." },
    { p: "30", n: "HAKKARİ", q: "Dağların ardında güneş her gün yeniden doğar." },
    { p: "31", n: "HATAY", q: "Medeniyetler beşiği sana sesleniyor: Dayanacaksın!" },
    { p: "32", n: "ISPARTA", q: "Gül şehrinden gül gibi kokulu günler seni bekliyor." },
    { p: "33", n: "MERSİN", q: "Akdeniz'in mavisi gibi huzur dolu günler yakında." },
    { p: "34", n: "İSTANBUL", q: "İki kıtayı birleştiren şehir gibi iki hayatı birleştireceksin." },
    { p: "35", n: "İZMİR", q: "Güzel İzmir! Özgürlüğün simgesi, terhisin habercisi." },
    { p: "36", n: "KARS", q: "Sarıkamış'ın karları erir, senin de günlerin eriyecek." },
    { p: "37", n: "KASTAMONU", q: "İstiklal'in başladığı yer, yeni başlangıcın olacak." },
    { p: "38", n: "KAYSERİ", q: "Erciyes'in zirvesi gibi hedefin yüksek olsun." },
    { p: "39", n: "KIRKLARELİ", q: "Trakya'nın yıldızı gibi parla, son günlere yaklaşıyorsun." },
    { p: "40", n: "KIRŞEHİR", q: "Neşet Ertaş'ın sazı gibi hayat güzel melodiler çalacak." },
    { p: "41", n: "KOCAELİ", q: "Sanayinin kalbi gibi çalış, hedefe ulaş." },
    { p: "42", n: "KONYA", q: "Mevlana: Dünle beraber gitti ne kadar söz varsa düne ait." },
    { p: "43", n: "KÜTAHYA", q: "Çini gibi ince işlenmiş sabır en güzel eseri çıkarır." },
    { p: "44", n: "MALATYA", q: "Kayısı diyarından tatlı haber: Terhis yaklaşıyor!" },
    { p: "45", n: "MANİSA", q: "Mesir macunu gibi her derde deva, biraz daha sabret." },
    { p: "46", n: "KAHRAMANMARAŞ", q: "Kahraman şehrin evladı kahraman olur, dayan!" },
    { p: "47", n: "MARDİN", q: "Taş evlerin arasından süzülen güneş gibi umut her yerden sızar." },
    { p: "48", n: "MUĞLA", q: "Mavi yolculuğun sonu beyaz bir sayfa olacak." },
    { p: "49", n: "MUŞ", q: "Ovada koşan atlar gibi özgür günler seni bekliyor." },
    { p: "50", n: "NEVŞEHİR", q: "Peri bacaları gibi hayaller gerçek olur, yeter ki inan." },
    { p: "51", n: "NİĞDE", q: "Aladağlar'ın dorukları gibi zirveye biraz daha tırman." },
    { p: "52", n: "ORDU", q: "Karadeniz'in incisi, sen de bu günlerin incisisin." },
    { p: "53", n: "RİZE", q: "Çay demlemek sabır ister, terhis de. İkisi de tatlı gelir." },
    { p: "54", n: "SAKARYA", q: "Zafer nehri gibi akışına bırak, hedefe ulaşacaksın." },
    { p: "55", n: "SAMSUN", q: "Bağımsızlığın başladığı yer. Bağımsız günlerin yakın." },
    { p: "56", n: "SİİRT", q: "Botan Vadisi gibi derin nefes al, rahatlayacaksın." },
    { p: "57", n: "SİNOP", q: "Karadeniz'in en mutlu şehri gibi sen de mutlu olacaksın." },
    { p: "58", n: "SİVAS", q: "Cumhuriyet'in temelinin atıldığı yer, temelin sağlam." },
    { p: "59", n: "TEKİRDAĞ", q: "Trakya'nın bereketli toprakları gibi güzel günler yeşerecek." },
    { p: "60", n: "TOKAT", q: "Yazmacılık gibi hayatına güzel desenler işlenecek." },
    { p: "61", n: "TRABZON", q: "Karadeniz fırtınası gibi bu günler de geçecek." },
    { p: "62", n: "TUNCELİ", q: "Munzur'un berrak suları gibi günlerin de berrak olacak." },
    { p: "63", n: "ŞANLIURFA", q: "Her zorlukla beraber bir kolaylık vardır." },
    { p: "64", n: "UŞAK", q: "Halılar gibi düğüm düğüm geçen günler güzel tablo olur." },
    { p: "65", n: "VAN", q: "Van Gölü'nün mavisi gibi huzurlu günler seni bekliyor." },
    { p: "66", n: "YOZGAT", q: "Boğazlıyan'ın kararlılığı gibi sen de kararlı ol." },
    { p: "67", n: "ZONGULDAK", q: "Madencilerin azmi gibi karanlıkta da ışığı bulacaksın." },
    { p: "68", n: "AKSARAY", q: "Ihlara Vadisi'nden esen rüzgar gibi ferahlık yakında." },
    { p: "69", n: "BAYBURT", q: "En küçük il ama yüreği en büyük. Senin de öyle." },
    { p: "70", n: "KARAMAN", q: "Söylenecek en güzel söz: Terhis oldum!" },
    { p: "71", n: "KIRIKKALE", q: "Silahların şehrinden barış müjdesi: Eve dönüş yakın." },
    { p: "72", n: "BATMAN", q: "Her kahraman gibi senin de hikayenin mutlu sonu var." },
    { p: "73", n: "ŞIRNAK", q: "Cudi'nin zirvesinden bak, yolun sonu görünüyor." },
    { p: "74", n: "BARTIN", q: "Amasra'nın güzelliği gibi güzel günler kapıda." },
    { p: "75", n: "ARDAHAN", q: "Soğuk gecelerin ardından sıcacık yuva seni bekliyor." },
    { p: "76", n: "IĞDIR", q: "Ağrı Dağı'nın eteğindeki umut seni eve taşıyacak." },
    { p: "77", n: "YALOVA", q: "Termal suları gibi rahatlatıcı haber: Az kaldı!" },
    { p: "78", n: "KARABÜK", q: "Safranbolu evleri gibi sağlam dur, temelin kuvvetli." },
    { p: "79", n: "KİLİS", q: "Küçük ama cesur şehir gibi cesaretinle son günleri aşacaksın." },
    { p: "80", n: "OSMANİYE", q: "Toprağın bereketli, yolun açık olsun." },
    { p: "81", n: "DÜZCE", q: "Her yeni gün düze çıkmak için bir fırsat. Haydi başlıyoruz!" }
];

console.log("✅ data.js yüklendi - " + CITIES.length + " il");